### ISSUE TITLE
Invalid MIT-MAGIC-COOKIE-1 keyxcb connect

### ISSUE THREAD

**Issue by SlimSnow** [AndreyBarmaley/xcb-window-capture#2]
ubuntu 20.04
when run debug mode

**Comment by AndreyBarmaley** [comment]
check the latest, please.
https://github.com/AndreyBarmaley/xcb-window-capture/commit/73547a964f4f7564a09008c9509c1d0f086085a1

**Comment by SlimSnow** [comment]
> check the latest, please. [73547a9](https://github.com/AndreyBarmaley/xcb-window-capture/commit/73547a964f4f7564a09008c9509c1d0f086085a1)

Thank you ,it works.
