### ISSUE TITLE
select any window,program crashed

### ISSUE THREAD

**Issue by SlimSnow** [AndreyBarmaley/xcb-window-capture#3]
select any window,click start button,program will crashed.
qt:5.12.5
ubuntu 20.04

**Comment by SlimSnow** [comment]
exception on ffmpegencoder.cpp line 147

if (0 >avformat_write_header(avfctx.get(),nullptr))

**Comment by AndreyBarmaley** [comment]
Look at the about tab, which version of ffmpeg is used?

**Comment by AndreyBarmaley** [comment]
please check version https://github.com/AndreyBarmaley/xcb-window-capture/commit/8a7a0d12f803ce21528ef7e1c848dfc99bed7d75 (more debug)

**Comment by AndreyBarmaley** [comment]
Today I installed ubuntu 20.04, minimal configuration (xorg server, icewm, g++, and others).
No problems, no crash, no memory leaks. Demo video.

https://user-images.githubusercontent.com/8620726/170432642-5f6bf5a6-cf53-4af0-865a-62c1b4a48b02.mp4

**Comment by SlimSnow** [comment]
Thank you for everything you've done. I'm sure it will help a lot of people.
